FROM python:3.8-slim

WORKDIR app

COPY requirements-torch.txt .
RUN pip3 install --upgrade pip \
    && pip3 install -r requirements-torch.txt

ENV path new5558
ENV is_pytorch True

EXPOSE 80

COPY . .

RUN python3 app/load_model.py

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
