name: Build & Deploy
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - run: echo ::set-env name=IMAGE_TAG::${GITHUB_REF:10}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          # tags: <org-name>/<repo-name>/<app-name>:${{ env.IMAGE_TAG }}
          # tags: docker.pkg.github.com/${{ github.repository_owner }}/<image-name>:${{ env.IMAGE_TAG }}
          tags: docker.pkg.github.com/${{ github.repository_owner }}/arv-example:latest

